### ISSUE TITLE
vlc will not save settings

### ISSUE THREAD

**Issue by lucas03** [XaF/TraktForVLC#25]
Hi,
I have a problem with vlc not saving rc settings. Here is my ubuntu question - http://askubuntu.com/questions/678617/vlc-does-not-save-my-settings

**Comment by spac3** [comment]
Hi lucas03,

I've updated your post.

**Comment by XaF** [comment]
Note that sometimes, settings are saved and active next time you start VLC, but not visibly active. It's the case when using `rc` instead of `oldrc` for instrance, as some versions of VLC do not seem to manage setting `rc` graphically.

However, as mentionned @spac3 as answer to your post on askubuntu, it can also be a problem of the settings file location on your system, that needs root privileges to be edited.

**Comment by lucas03** [comment]
ok, thanks

**Comment by meetsc** [comment]
Hi,

I am also facing the same issue. It is not the issue with permissions as I was able to run vlc as root. But still, the settings were not saved.
