### ISSUE TITLE
Problem "loading"  .plist

### ISSUE THREAD

**Issue by odlmag** [XaF/TraktForVLC#40]
Hello,

I'm on a Mac OSX.
I have similar problems as some other here, as I can't save the VLC settings and the .plist doesn't seem to be saved when using the "load" command.

==== VLC problem =====

Starting with the VLC problem, i'm picking up where "alltimemarr" started the search in a previous thread.
If I set the settings according to the instructions, and then restart VLC it gives me similar results when using the terminal command
`telnet localhost 4222`
(unable to connect)

Changing the setting sometimes let me access it with the terminal, and sometimes it gives me the same results.

Typing the commands:
`echo $VLC_PLUGIN_PATH` result = white line
`ls /usr/lib | grep vlc`                result = nothing
`ls /usr/local/lib | grep vlc`        result = no such file...

Typing:
`ls -AlsR /Applications/VLC.app/Contents/MacOS/`
gives me a big list of which im not sure what to do...?
This is where "altimemarr" dropped out of the discussion, so where to go from here?

===== .plist problem ======

So here's my .plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>org.user.TraktForVLC</string>
    <key>ProgramArguments</key>
    <array>
        <string>[/Library/Frameworks/Python.framework/Versions/2.7/bin/python]</string>
        <string>[/Users/Magnus/TraktForVLC/TraktForVLC.py]</string>
    </array>
    <key>WorkingDirectory</key>
    <string>[/Users/Magnus/TraktForVLC]</string>
    <key>RunAtLoad</key>
    <true />
    <key>LaunchOnlyOnce</key>
    <true />
    <key>KeepAlive</key>
    <true />
</dict>
</plist>
```

I can find a "python" file at the directory /usr/bin/python/, but typing `which python` in the terminal gives me the above path. (I guess i have two different python, since I installed a new one yesterday when installing CouchPotato?)

When typing in the terminal:
`launchctl load ~/Library/LaunchAgents/org.TraktForVLC.plist`
nothing seems to happen. And when I check `launchctl list` I can't find it in the list...
What am I missing?

====== Misc =====

When checking through the "TraktClient.py" code there are some code where username & password are requested, as the Trakt.tv code and tokens.
Should these be manually updated or am I out of bounds looking in there?
I have also put the code from Trakt.tv in ".ini" file, but I read somewhere that these codes get outdated after some time?

Long post, sorry!
But glad if someone could help out!

/ odlmag

**Comment by XaF** [comment]
### VLC Problem
First thing, if the problem is about not having the VLC settings saved when you put 'rc' manually, it is highly possible that the 'rc' is still active even if you don't see it in the list. It is a VLC problem. Of course, if you edit and save the settings again and that case is empty (not containing 'rc' anymore), it will then be inactive... It is a VLC problem, unfortunately. In my case, 'rc' is active even through it doesn't appear in the list (I get 'oldrc' by checking 'RC', but 'oldrc' is not as good as 'rc' for what `TrackForVLC` is doing).

If the problem is at another level, could you please explain it better? I would need to know what are the results of running `TraktForVLC` in your case (DEBUG mode -> log file).

### .plist Problem
I'm not using Mac so that's just a wild guess to help you. However, I think your file is not formatted the right way. You left the `[` and `]` around your values. For instance, you put:
```
        <string>[/Library/Frameworks/Python.framework/Versions/2.7/bin/python]</string>
```
Where you should have put:
```
        <string>/Library/Frameworks/Python.framework/Versions/2.7/bin/python</string>
```

### Misc
The `TraktClient.py` file has been built to sustain the old way of connection to Trakt during the changes in the API previously, as both ways were valid, to let time to users to change from one way to the other. You should now use the PIN auth. The PIN auth expires after a period of time, but if you launch `TraktForVLC` before it expires, it will automatically be replaced by authentication tokens that will allow `TraktForVLC` to authenticate to Trakt. `TraktForVLC` will then automatically renew those tokens on a regular basis without needing your intervention, so you should be good then!

**Comment by odlmag** [comment]
Hi,

Thanks for the quick reply!

At work now, but will check when I get home!

Regarding VLC it seems the settings revert back to default settings after I restart it.
But usually only the check box at "**remote control interface**".
The line below still says "**rc**" when I open up VLC, but when i re-check the "**remote control interface**" check box the line goes back to "**oldrc**". (Which i then change to "rc" again).

On the "**TCP Command input**" the command "**localhost:4222**" usually stays between restarts, however I noticed on my last restart that it had dissapeared as well...

But when changing all the settings I have been able to acces the VLC through
**telnet localhost 4222**

So **TraktForVLC** should work if the telnet command in treminal works?

I will remove the brackets from the .plist to see if it makes any difference!
Should be that mistake!

BR
Odlmag

**Comment by odlmag** [comment]
Hi again,

Just giving a status report.

Taking out the brackets [ ] sure worked fine!

Tried it just now, and TraktForVLC worked just fine.

Regarding the VLC problem, seems it "looks" like the settings aren't intact when i re-start it.
(The remote control interface check box isn't checked)
But it seems to work anyway

So thanks for the help!
