### ISSUE TITLE
Help needed with Scheduling a task

### ISSUE THREAD

**Issue by Denomenator** [XaF/TraktForVLC#46]
So, i have got everything done except running traktforVLC on VLC startup. How can i do that? I am at this part: [Automatic Start](https://github.com/XaF/TraktForVLC#on-windows)

**Comment by XaF** [comment]
Well... you can directly [find that answer by yourself on Microsoft's website](http://windows.microsoft.com/en-au/windows/schedule-task#1TC=windows-7).

**Comment by Denomenator** [comment]
would the trigger be when a specific event is logged? If so, what would the log be?

**Comment by khiven** [comment]
It is be really easy to set up the start_process.bat to start when Windows start XaF, however making it so it only starts when vlc.exe starts and stop the process when vlc.exe stops is not that easy. Is there a way to do it? The task scheduller will ask for event log which I assume it has to be "Application" then source I assume it has to be "Application" then EventID I have no idea what event Id vlc.exe throws at start or at end . 

Can you please help us? It would be really nice to have the process running only when vlc is and stop when vlc stops. Nobody likes to have a background process running all day even if its light like this one.

Thank you in advance.

**Comment by XaF** [comment]
I don't actually know of a way to do what you are asking.
`TraktForVLC` has been built to be running in the background all the time, and to only check if VLC is running. No network call is done if VLC is not running, which makes its background work very lightweight. The best way to do what you are asking for would be to have a VLC plugin instead of an external application, but this would be much more difficult to maintain and improve!

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
