### ISSUE TITLE
Starting VLC Using Arguments by Default

### ISSUE THREAD

**Issue by dannymichel** [XaF/TraktForVLC#48]
How do i start VLC on mac using these command arguments by default? Like if i wanted to run it by default all the time using ~/Applications/VLC.app/Contents/MacOS/VLC --extraintf=rc --rc-host=localhost:4222

**Comment by XaF** [comment]
I can't really answer that question as I'm not using Mac, but if somebody can provide it, it could be useful! :)

**Comment by AmitSinghTGA** [comment]
**Automator**
Use Automator to create an application that in effect launches VLC with command line arguments.

Start Automator and select to create an Application. Double-click Run Shell Script in the Library/Utilities folder and replace the text content — cat — with the following:

`~/Applications/VLC.app/Contents/MacOS/VLC --extraintf=rc --rc-host=localhost:4222`
If it doesn't work, remove ~ for sure.
And then Save anywhere you like.

**ICON**
To replace this application's icon, Get Info on your real VLC, click on the icon on the top left, press Cmd-C, Get Info on your VLC Automator app, click the icon, and press Cmd-V.

Give it a try. Hope it works.

I and using the same trick because my VLC is not storing the RC values at all.

**Comment by spazure** [comment]
> Start Automator and select to create an Application. Double-click Run Shell Script in the Library/Utilities folder and replace the text content — cat — with the following:

> ~/Applications/VLC.app/Contents/MacOS/VLC --extraintf=rc --rc-host=localhost:4222
If it doesn't work, remove ~ for sure.
And then Save anywhere you like.

Not OP, but was googling and found this solution. Signed up just to let you know that It worked perfect for me, thanks!

**Comment by dnicolson** [comment]
Another option is to manually edit the `~/Library/Preferences/org.videolan.vlc/vlcrc` file directly, changing line 1064 to `rc-host=localhost:4222` and line 3459 to `extraintf=rc`.

It will be overwritten on quitting VLC, but only if you have navigated directly to the Lua setting.

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
