### ISSUE TITLE
TraktError: Unable to start episode: None (404 Not Found)

### ISSUE THREAD

**Issue by hnk** [XaF/TraktForVLC#6]
See this gist for debug log:
https://gist.github.com/65a03dcee7b197c2a771

This fails consistently when letting the episode run for a while.

**Comment by XaF** [comment]
I'm unable to open your gist, maybe because the ongoing DDoS attack on github. Can you post your log on another website like pastebin?

**Comment by hnk** [comment]
Now I understand, thanks for clarifying that.
But I do wonder: The show is [in trakt itself](http://trakt.tv/shows/better-off-ted). So it should be able to correctly scrobble this. I see that the script only sends the imdb id in the json data. Why does it not find the show in trakt?

Sorry, I did not read much into the codebase at all so I have to ask questions like that :pensive:

**Comment by XaF** [comment]
Usually, [trakt.tv](http://trakt.tv) uses the information it gets from [thetvdb.com](http://thetvdb.com) to load shows, seasons and episodes. [thetvdb.com](http://thetvdb.com) also gives it the informations on its internal id for the shows, seasons and episodes that [trakt.tv](http://trakt.tv) is getting, but also the shows, seasons and episodes imdb IDs (For the episode you were watching, here is [the data that is available on thetvdb.com](http://thetvdb.com/?tab=episode&seriesid=84021&seasonid=37940&id=413862&lid=7)).

So, we can see that the imdb ID is rightly referenced (we also saw that ```TraktForVLC``` was able to find that ID), as [you can verify directly by the URL of that episode on imdb](http://www.imdb.com/title/tt1346400/).

I now tried to do the request manually to the [trakt.tv](http://trakt.tv) api, and it also returned me a 404 error. That error, for the ```scrobble/start``` call, means that the element we were trying to scrobble was not found. I thus tried to call that method using the show ID and the season and episode number, and I got that in return along with a 201 return code (meaning it worked):

```json
{
    "action": "start",
    "progress": 7,
    "sharing": {
        "facebook": false,
        "twitter": false,
        "tumblr": false
    },
    "episode": {
        "season": 1,
        "number": 1,
        "title": "Pilot",
        "ids": {
            "trakt": 399481,
            "tvdb": 413862,
            "imdb": "",
            "tmdb": 391090,
            "tvrage": 775469
        }
    },
    "show": {
        "title": "Better Off Ted",
        "year": 2009,
        "ids": {
            "trakt": 7731,
            "slug": "better-off-ted",
            "tvdb": 84021,
            "imdb": "tt1235547",
            "tmdb": 7777,
            "tvrage": null
        }
    }
}
```

You can thus see, in the "ids" of the "episode" object, that the "imdb" line is blank. It means that [trakt.tv](http://trakt.tv) hasn't that imdb ID in its database (it has a blank string instead), even if [thetvdb.com](http://thetvdb.com) references it.

It is possible that it's only because the episode hasn't been updated on trakt since the entry on thetvdb has been updated to add the imdb ID. But mostly, it means the bug comes from [trakt.tv](http://trakt.tv) and not from ```TraktForVLC```. On the other side, the commit 91bda7 was aimed to work for episodes of shows for which we didn't have the imdb ID in thetvdb, so I will probably enhance it to make it work for cases where [trakt.tv](http://trakt.tv) is not up to date.
