### ISSUE TITLE
tutorial for noobs.

### ISSUE THREAD

**Issue by gadour97** [XaF/TraktForVLC#85]
Man please do a video tutorial on how to install/configure it with vlc i can't understand shit. it must be pretty basic for you but i've tried my best and it can't be done. 
there are other people who find it hard to : https://support.trakt.tv/forums/188762-general/suggestions/14865675-vlc-plugin
I suggestedon reddit that someone do the tutorial but no one answered 
https://www.reddit.com/r/trakt/comments/7bcpb6/scrobble_from_vlc/ 
please

**Comment by XaF** [comment]
Hi @gadour97 

I realize the current setup situation is not the best. However, I'm currently working on a whole new version of `TraktForVLC` that I hope will integrate way better with VLC, and should be easier to install and setup. I cannot guarantee it at the moment as it is work under way, and not having a Windows computer myself makes it harder for me to test-proof it, but I have good hopes.
I prefer spending the time I can give to `TraktForVLC` for this new version, which is why I cannot take the time to fix bugs/make detailed tutorials -- added to the fact that not having Windows does not help in making a Windows tutorial.

Please bear with me.

**Comment by Francis2b** [comment]
@gadour97 if you have a mac computer I wrote a tutorial on my blog https://francisuniverse.wordpress.com/2017/07/22/install-traktforvlc-on-macos/

**Comment by gadour97** [comment]
Windows 10 😞
________________________________
De : Francis <notifications@github.com>
Envoyé : lundi 12 février 2018 14:14
À : XaF/TraktForVLC
Cc : gadour; Mention
Objet : Re: [XaF/TraktForVLC] tutorial for noobs. (#85)


@gadour97<https://github.com/gadour97> if you have a mac computer I wrote a tutorial on my blog https://francisuniverse.wordpress.com/2017/07/22/install-traktforvlc-on-macos/

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
