### ISSUE TITLE
lua error - Invalid Argument

### ISSUE THREAD

**Issue by danteali** [XaF/TraktForVLC#91]
On Windows 10, I get the following error in the VLC log file...

> lua error: Error loading script C:\Program Files\VideoLAN\VLC\lua\intf\trakt.luac: trakt.lua:313: /T:/Media/Video/TV/Band.of.Brothers/Season.01/Band.of.Brothers.s01e01.Currahee.1080p.mp4: Invalid argument

Installation and activation work fine. The Windows Service is running. I tried v2.0.0a1 and v2.0.0a1.dev. And tried re-installing VLC. Also tried both x64 and x86 versions of VLC (with corresponding TraktForVLC version).

Same error every time. Any ideas?

**Comment by Ale46** [comment]
Changing line 313 of trakt.lua with this:

```lua 
local fil = assert(io.open(string.sub(fileName, 2), 'rb'))
```

fixed the problem for me. But that's NOT the right way to fix the bug, obviously.. I think that's something related with filename under Windows and having `DRIVE_LETTER:/PATH/FILENAME` rather than `/DRIVE_LETTER:/PATH/FILENAME` should solve the bug. 

In my case I had to remove the first two characters to achieve the correct pattern, probably I had some white-space or whatever at the start of the filename and removing the first char was not enough. That's probably something to consider for a real fix.

After the edit I'm getting another error message:
```
[000000000264bb90] [trakt] main interface error: connection failed: Connection refused by peer
[000000000264bb90] [trakt] lua interface error: (call_helper) Command: "date" "--format" "%s.%f"
[000000000264bb90] [trakt] lua interface error: (call_helper) Command exited with code -1
```
I don't think it's related to my edit but I want to be sure before opening a new issue..

**Comment by danteali** [comment]
Where is your trakt.lua file?

I only have a trakt.luac file under .../VideoLAN/VLC/lua/intf

You should open an issue for that other error - I get that too.

**Comment by Ale46** [comment]
@danteali I just deleted the luac file and dropped [trakt.lua](https://github.com/XaF/TraktForVLC/blob/master/trakt.lua) from this repo..

**Comment by XaF** [comment]
Is there a reason why there is a `/` at the beginning of the path ?!

**Comment by XaF** [comment]
Hm, it seems the URI provided by VLC on WIndows 10 is not in the right format. That's kinda weird... I'm wondering why there's a `/` at the beginning...

**Comment by XaF** [comment]
Found the problem for this issue. Will push a fix soon.

**Comment by danteali** [comment]
Perfect!

Seems to be working fine now on the newest dev version

**Comment by XaF** [comment]
Thanks for the confirmation!
